### ISSUE TITLE
Pnotify for angular throws syntax error in IE.

### ISSUE THREAD

**Issue by Sonik20** [sciactive/pnotify#343]
@hperrin Can you please help here. Thanks
![2018-06-01_15-23-22](https://user-images.githubusercontent.com/24838052/40835039-0024cd04-65b0-11e8-8939-d630b5e1a3a8.png)

**Comment by munisravan** [comment]
I'm facing the same problem, can someone help in this context.

**Comment by smithk58** [comment]
This is happening because they're using arrow functions, which can't be polyfilled back into older browsers like IE. So you'll have to use the ES5 js files if you want to support older browsers. Those don't appear to import nicely into Angular 6 though for some reason, but I'll update this if I figure that part out.

**Comment by munisravan** [comment]
Thank you @smithk58  for your hepl, your solution fixed my app in IE.

**Comment by hperrin** [comment]
Thanks, @smithk58!
